server:
  port: 2240
spring:
  application:
    name: Employee-jpastreamer
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true